theme = "nordic"

[editor]
line-number = "relative"
bufferline = "multiple"
popup-border = "all"
scrolloff = 8
rulers = [120]
color-modes = true
mouse = true
text-width = 120
end-of-line-diagnostics = "hint"
jump-label-alphabet = "tnseriaodhfuplwygmbjvkqxcz"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.inline-diagnostics]
max-wrap = 30
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "file-name", "spinner"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
character = "╎"
render = false

# Keybindings // Colemak-dh

# normal
[keys.normal]
"," = { "," = "@<esc>" }
m = "move_char_left"
n = "move_line_down"
e = "move_line_up"
i = "move_char_right"
h = "insert_mode"
H = "insert_at_line_start"
l = "move_next_word_end"
L = "move_next_long_word_end"
k = "search_next"
K = "search_prev"
N = "join_selections"
"A-N" = "join_selections_space"
E = "keep_selections"
"A-E" = "remove_selections"

C-n = "@4n"
C-e = "@4e"
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
- = "select_all"

[keys.normal.j]
m = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.normal.space.w]
m = "jump_view_left"
n = "jump_view_down"
e = "jump_view_up"
i = "jump_view_right"

h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
C-h = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"

[keys.normal.C-w]
m = "jump_view_left"
n = "jump_view_down"
e = "jump_view_up"
i = "jump_view_right"
M = "swap_view_left"
N = "swap_view_down"
E = "swap_view_up"
I = "swap_view_right"

h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
C-h = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"

[keys.normal.z]
n = "scroll_down"
e = "scroll_up"

[keys.normal.Z]
n = "scroll_down"
e = "scroll_up"

# insert
[keys.insert]
"," = { "," = "@<esc>" }

# select
[keys.select]
"," = { "," = "@<esc>" }
m = "extend_char_left"
n = "extend_line_down"
e = "extend_line_up"
i = "extend_char_right"
h = "insert_mode"
H = "insert_at_line_start"
l = "extend_next_word_end"
L = "extend_next_long_word_end"
k = "search_next"
K = "search_prev"
N = "join_selections"
"A-N" = "join_selections_space"
E = "keep_selections"
"A-E" = "remove_selections"

C-n = "@4n"
C-e = "@4e"
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
- = "select_all"

[keys.select.j]
m = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

# space
[keys.normal.space]
e = "hover"

k = "no_op"
